### ISSUE TITLE
not any issues

### ISSUE THREAD

**Issue by luckyxiaomo** [yuri-li/study-kotlin#1]
first, i am sorry for my poor English.

i find an issue submitted by you.   [https://github.com/JetBrains/Exposed/issues/193](url)
how can you fixed the issue?

and this issue submitted by me.   [https://github.com/JetBrains/Exposed/issues/566](url)

**Comment by yuri-li** [comment]
不好意思哈，不太熟悉github。你的问题，我已经回复了
https://github.com/JetBrains/Exposed/issues/566
